services:
  web:
    build: ./web
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2025_db"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    env_file:
      - .env
    
  scheduler:
    build: ./scheduler
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2025_db"
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ubuntu
      RABBITMQ_DEFAULT_PASS: ubuntu
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-net
    env_file:
      - .env
  
  sh_ip_int_br_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.sh_ip_int_br
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2025_db"
    depends_on:
      - rabbitmq
      - mongo
      - scheduler
    networks:
      - app-net

  sh_run_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.sh_run
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2025_db"
    depends_on:
      - rabbitmq
      - mongo
      - scheduler
    networks:
      - app-net

  modify_interface_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.modify_interface
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2025_db"
    depends_on:
      - rabbitmq
      - mongo
      - scheduler
    networks:
      - app-net

volumes:
  mongo-data:
  rabbitmq_data:

networks:
  app-net: