FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY database.py .
COPY sh_run_worker.py .
COPY sh_run_module ./sh_run_module
CMD ["python", "sh_run_worker.py"]
