FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY database.py .
COPY modify_interface_worker.py .
COPY modify_interface_module ./modify_interface_module
CMD ["python", "modify_interface_worker.py"]
