FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY database.py  .
COPY sh_ip_int_br_worker.py .
COPY sh_ip_int_br_module ./sh_ip_int_br_module
CMD ["python", "sh_ip_int_br_worker.py"]
