apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa2025-msapp-web
  namespace: devops-tools
spec:
  project: ipa-2025
  source:
    repoURL: 'https://github.com/MAK1z/Cisco123--IPA2025'
    targetRevision: HEAD
    path: web/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ipa-2025
  syncPolicy:
    automated:
      prune: true
      selfHeal: true/ipa2025-msapp'
    targetRevision: HEAD
    path: web/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ipa-2025
  syncPolicy:
    automated:
      prune: true
      selfHeal: true